# Generated by Django 3.0.8 on 2020-07-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-user',), 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
    ]
