# Generated by Django 3.0.8 on 2020-07-11 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20200709_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDetail',
            new_name='Project',
        ),
    ]
