# Generated by Django 3.0.8 on 2020-07-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
